#!/usr/bin/env bash
# Session picker with switch / rename / kill / new bindings.
# - Enter:  switch-client to selected session
# - Ctrl-R: rename selected session via second fzf popup
# - Ctrl-X: kill selected session
# - Ctrl-C: create a new session via second fzf popup

set -u

prompt_inline() {
    local header=$1 default=$2 out ec
    out=$(printf '\n' | fzf-tmux -p 50%,3 --reverse \
        --print-query --query "$default" \
        --bind 'enter:print-query+accept' \
        --header "$header" \
        --no-info 2>/dev/null)
    ec=$?
    [ $ec -ne 0 ] && return 1
    printf '%s\n' "$out" | sed -n 1p
}

create_session() {
    local new
    new=$(prompt_inline 'new session name:' '')
    [ -z "$new" ] && return 0
    if tmux has-session -t="$new" 2>/dev/null; then
        tmux switch-client -t "$new"
    else
        TMUX= tmux new-session -d -s "$new"
        tmux switch-client -t "$new"
    fi
}

selected=$(tmux list-sessions -F '#{session_name}	(#{session_windows} windows)#{?session_attached, [attached],}' | \
    fzf-tmux -p 60%,40% --reverse \
        --delimiter '\t' --with-nth 1,2 \
        --header 'enter: switch / ctrl-r: rename / ctrl-x: kill / ctrl-c: new' \
        --expect=ctrl-r,ctrl-x,ctrl-c)

key=$(printf '%s\n' "$selected" | sed -n 1p)
line=$(printf '%s\n' "$selected" | sed -n 2p)
name=${line%%$'\t'*}

if [ "$key" = 'ctrl-c' ]; then
    create_session
    exit 0
fi

[ -z "$name" ] && exit 0

case "$key" in
    ctrl-r)
        new=$(prompt_inline "rename '$name' to:" "$name")
        if [ -n "$new" ] && [ "$new" != "$name" ]; then
            tmux rename-session -t "$name" "$new"
        fi
        ;;
    ctrl-x)
        tmux kill-session -t "$name"
        ;;
    *)
        tmux switch-client -t "$name"
        ;;
esac
