[tools]
node = "latest"
deno = "latest"
bun = "latest"
uv = "latest"
python = "latest"
usage = "latest"
pnpm = "10.9.0"
yarn = "latest"
"pipx:tldr" = "latest"
"github:duckdb/duckdb" = "latest"
"npm:ccusage" = "latest"
"npm:@moonbit/moonbit-lsp" = "latest"
go = "latest"
moonbit = "latest"

[settings]
experimental = true

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "bun"
