# navigation {{{
[[snippets]]
name = "zoxide"
trigger = "c"
snippet = "z"

[[snippets]]
name = "zoxide"
trigger = "cd"
snippet = "z"
# }}}

# listing (eza) {{{
[[snippets]]
name = "eza"
trigger = "l"
snippet = "eza --group-directories-first"

[[snippets]]
name = "eza --git"
trigger = "ls"
snippet = "eza --group-directories-first --git"

[[snippets]]
name = "eza -a"
trigger = "la"
snippet = "eza --group-directories-first -a"

[[snippets]]
name = "eza --git -l"
trigger = "ll"
snippet = "eza --group-directories-first --git -l"

[[snippets]]
name = "eza --git -la"
trigger = "lla"
snippet = "eza --group-directories-first --git -la"

[[snippets]]
name = "eza --tree"
trigger = "tree"
snippet = "eza --group-directories-first --tree"

[[snippets]]
name = "eza sort newest first"
trigger = ":n"
snippet = "-s modified -r"
global = true
context = '^eza\s+'

[[snippets]]
name = "eza sort largest first"
trigger = ":s"
snippet = "-s size -r"
global = true
context = '^eza\s+'
# }}}

# shell / coreutils {{{
[[snippets]]
name = "history"
trigger = "h"
snippet = "fc -lt '%F %T' 1"

[[snippets]]
name = "cp/mv/rm -i"
trigger-pattern = "^(cp|mv|rm)$"
snippet = "$abbr -i"
evaluate = true

[[snippets]]
name = "mkdir -p"
trigger = "mkdir"
snippet = "mkdir -p"

[[snippets]]
name = "diff -U1"
trigger = "diff"
snippet = "diff -U1"

[[snippets]]
name = "curl --compressed"
trigger = "curl"
snippet = "curl --compressed"

[[snippets]]
name = ">/dev/null 2>&1"
trigger = "null"
snippet = ">/dev/null 2>&1"
global = true
# End of shell / coreutils }}}

# tools {{{
[[snippets]]
name = "tmux -u"
trigger = "t"
snippet = "tmux -u"

[[snippets]]
name = "devbox"
trigger = "dv"
snippet = "devbox"

[[snippets]]
name = "mo --no-open"
trigger = "mo"
snippet = "mo --no-open"
# End of tools }}}

# nvim {{{
[[snippets]]
name = "nvim"
trigger = "ni"
snippet = "nvim"

[[snippets]]
name = "nvim ."
trigger = "nid"
snippet = "nvim ."
# End of nvim }}}

# nix {{{
[[snippets]]
name = "nix"
trigger = "nx"
snippet = "nix"

[[snippets]]
name = "nix develop"
trigger-pattern = "ni?d"
snippet = "nix develop"

[[snippets]]
name = "nix develop -c zsh (shorthand)"
trigger-pattern = "ni?d?z"
snippet = "nix develop -c zsh"

[[snippets]]
name = "nix develop -c zsh"
trigger = "z"
snippet = "-c zsh"
global = true
context = '^nix\s+develop\s+'
# End of nix }}}

# docker {{{
[[snippets]]
name = "docker"
trigger = "d"
snippet = "docker"

[[snippets]]
name = "docker compose"
trigger = "dc"
snippet = "docker compose"

[[snippets]]
name = "docker compose"
trigger-pattern = "^co?$"
snippet = "compose"
global = true
context = '^docker\s+'
# End of docker }}}

# python {{{
[[snippets]]
name = "uv run python *.py"
trigger-pattern = '^(?<file>.+\.py)$'
snippet = "uv run python $file"
evaluate = true
# End of python }}}

# awk column shorthand {{{
[[snippets]]
name = "awk print $N"
trigger-pattern = '^\.\d+$'
snippet = "awk '{ print ${trigger/./$} }'"
evaluate = true
global = true
# End of awk }}}

# date {{{
[[snippets]]
name = "yyyymmdd date expansion"
trigger-pattern = '^yyyy(?<sep1>.?)mm(?<sep2>.?)dd(?<diff>[+-]\d+)?$'
snippet = '$(date "+%Y${sep1}%m${sep2}%d" -d "${diff:-0}day")'
evaluate = true
global = true
# }}}
