[[snippets]]
name = "zoxide"
trigger = "c"
snippet = "z"

[[snippets]]
name = "zoxide"
trigger = "cd"
snippet = "z"

[[snippets]]
name = "l"
trigger = "l"
snippet = "eza --group-directories-first"

[[snippets]]
name = "ls"
trigger = "ls"
snippet = "eza --group-directories-first --git"

[[snippets]]
name = "la"
trigger = "la"
snippet = "eza --group-directories-first -a"

[[snippets]]
name = "ll"
trigger = "ll"
snippet = "eza --group-directories-first --git -l"

[[snippets]]
name = "lla"
trigger = "lla"
snippet = "eza --group-directories-first --git -la"

[[snippets]]
name = "tree"
trigger = "tree"
snippet = "eza --group-directories-first --tree"

[[snippets]]
name = "sort newest first"
trigger = ":n"
snippet = "-s modified -r"
global = true
context = '^eza\s+'

[[snippets]]
name = "sort largest first"
trigger = ":s"
snippet = "-s size -r"
global = true
context = '^eza\s+'

[[snippets]]
name = "h"
trigger = "h"
snippet = "fc -lt '%F %T' 1"

[[snippets]]
name = "safe"
trigger-pattern = "^(cp|mv|rm)$"
snippet = "$abbr -i"
evaluate = true

[[snippets]]
name = "mkdir with parents"
trigger = "mkdir"
snippet = "mkdir -p"

[[snippets]]
name = "diff"
trigger = "diff"
snippet = "diff -U1"

[[snippets]]
name = "curl"
trigger = "curl"
snippet = "curl --compressed"

[[snippets]]
name = "tmux -u"
trigger = "t"
snippet = "tmux -u"

[[snippets]]
name = "devbox"
trigger = "dv"
snippet = "devbox"

[[snippets]]
name = "d"
trigger = "d"
snippet = "docker"

[[snippets]]
name = "dc"
trigger = "dc"
snippet = "docker compose"

[[snippets]]
name = "docker compose"
trigger-pattern = "^co?$"
snippet = "compose"
global = true
context = '^docker\s+'

[[snippets]]
name = "uv run python *.py"
trigger-pattern = '^(?<file>.+\.py)$'
snippet = "uv run python $file"
evaluate = true

[[snippets]]
name = "mo"
trigger = "mo"
snippet = "mo --no-open"

[[snippets]]
name = ">/dev/null 2>&1"
trigger = "null"
snippet = ">/dev/null 2>&1"
global = true
