# basics {{{
[[snippets]]
name = "git"
trigger = "g"
snippet = "git"

[[snippets]]
name = "git status -sb"
trigger = "gst"
snippet = "git status -sb"

[[snippets]]
name = "git status"
trigger-pattern = "^st?$"
snippet = "status"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git add ."
trigger = "gad"
snippet = "git add ."
# }}}

# staging / restore {{{
[[snippets]]
name = "git add"
trigger-pattern = "^ad?$"
snippet = "add"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git add -vA"
trigger = "aa"
snippet = "add -vA"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git restore [--staged]"
trigger-pattern = "^re?s(?<staged>s)?$"
snippet = "restore${staged+ --staged}"

global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git restore --staged (flag)"
trigger = "s"
snippet = "--staged"
global = true
context = '^git\s+restore\s+'
# }}}

# diff {{{
[[snippets]]
name = "git diff [--staged] [--ignore-all-space]"
trigger-pattern = "^df?(?<staged>s)?(?<ignore>i)?$"
snippet = "diff${staged+ --staged}${ignore+ --ignore-all-space}"
evaluate = true
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git diff HEAD~N HEAD"
trigger-pattern = '^(?<n>\d+)$'
snippet = "HEAD~$n HEAD"
evaluate = true
global = true
context = '^git\s+diff\s+'
# }}}

# commit {{{
[[snippets]]
name = "git commit"
trigger = "c"
snippet = "commit"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git commit -m"
trigger = "cm"
snippet = "commit -m \"{}\""
cursor = "{}"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git commit --amend --no-edit"
trigger = "cam"
snippet = "commit --amend --no-edit"
global = true
context = '^git\s+\S+$'
# }}}

# rebase / merge / cherry-pick {{{
[[snippets]]
name = "git rebase|merge|cherry-pick --abort"
trigger = "a"
snippet = "--abort"
global = true
context = '^git\s+(cherry-pick|rebase|merge)\s+'

[[snippets]]
name = "git rebase|merge|cherry-pick --continue"
trigger = "c"
snippet = "--continue"
global = true
context = '^git\s+(cherry-pick|rebase|merge)\s+'
# }}}

# push {{{
[[snippets]]
name = "git push origin HEAD"
trigger = "gpoh"
snippet = "git push origin HEAD"

[[snippets]]
name = "git push"
trigger = "ph"
snippet = "push"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git push --force-with-lease"
trigger = "f"
snippet = "--force-with-lease"
global = true
context = '^git\s+push\s+'
# }}}

# fetch / pull {{{
[[snippets]]
name = "git fetch [--prune]"
trigger-pattern = "^fe?(?<prune>p)?$"
snippet = "fetch${prune+ --prune}"
evaluate = true
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git pull"
trigger = "pl"
snippet = "pull"
global = true
context = '^git\s+\S+$'
# }}}

# branch / switch {{{
[[snippets]]
name = "git branch [-v/-vv]"
trigger-pattern = "^br?(?<verbose>v{1,2})?$"
snippet = "branch${verbose+ -$verbose}"
evaluate = true
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git branch [-v/-vv] (flag)"
trigger-pattern = "^(v{1,2})$"
snippet = "-$abbr"
evaluate = true
global = true
context = '^git\s+branch\s+'

[[snippets]]
name = "git switch"
trigger = "sw"
snippet = "switch"
global = true
context = '^git\s+\S+$'
# }}}

# log / graph {{{
[[snippets]]
name = "git log -n 10 (formatted)"
trigger = "gl"
snippet = "git log --pretty=format:\"%C(auto)%h (%C(blue)%cd%C(auto))%d %s %C(blue)%cn%Creset\" --date=format:\"%Y/%m/%d %H:%M:%S\" -n 10"

[[snippets]]
name = "git log [--oneline] [--name-status]"
trigger-pattern = "^l(?<oneline>o)?(?<filename>f)?$"
snippet = "log${oneline+ --oneline}${filename+ --name-status}"
evaluate = true
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git log -N"
trigger-pattern = '^(?<n>\d+)$'
snippet = "-$n"
evaluate = true
global = true
context = '^git\s+log\s+'

[[snippets]]
name = "git log --graph"
trigger-pattern = "gr|graph"
snippet = "log --graph --date=short --decorate=short --pretty=format:'%Cgreen%h %Creset%cn %Cred%d %Creset%s'"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git log --grep"
trigger-pattern = '^gp?$'
snippet = '--grep="{}"'
cursor = "{}"
global = true
context = '^git\s+log\s+\S+$'
# }}}

# stash {{{
[[snippets]]
name = "git stash"
trigger = "sh"
snippet = "stash"
global = true
context = '^git\s+\S+$'

[[snippets]]
name = "git stash push -m"
trigger = "ph"
snippet = "push -m"
global = true
context = '^git\s+stash\s+'
# }}}

# worktree {{{
[[snippets]]
name = "git wt"
trigger = "w"
# git-wt
snippet = "wt"
global = true
context = '^git\s+\S+$'
# }}}

# refs {{{
[[snippets]]
name = "git current branch name"
trigger = "B"
snippet = "$(git symbolic-ref --short HEAD)"
evaluate = true
global = true
context = '^git\s+'

[[snippets]]
name = "git main/master"
trigger = "M"
snippet = "$(git show-ref --verify --quiet refs/heads/main && echo main || echo master)"
evaluate = true
global = true
context = '^git\s+'
# }}}

# tag version bump {{{
[[snippets]]
name = "git tag patch bump"
trigger = "T+"
snippet = '$(semver -i patch "$(git describe --abbrev=0 --tags @ 2>/dev/null)")'
evaluate = true
global = true
context = '^git\s+'

[[snippets]]
name = "git tag minor bump"
trigger = "T++"
snippet = '$(semver -i minor "$(git describe --abbrev=0 --tags @ 2>/dev/null)")'
evaluate = true
global = true
context = '^git\s+'

[[snippets]]
name = "git tag major bump"
trigger = "T!"
snippet = '$(semver -i major "$(git describe --abbrev=0 --tags @ 2>/dev/null)")'
evaluate = true
global = true
context = '^git\s+'
# }}}
