bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "Reload Config"

# New {{{
bind c new-window -c '#{pane_current_path}'
bind C-c new-session
# }}}

# Switch session {{{
# default '(', ')'
# bind ( switch-client -p
# bind ) switch-client -n
# }}}

# Switch window {{{
bind p previous-window
bind n next-window
bind C-p previous-window
bind C-n next-window
# }}}

# Swap window {{{
bind P swap-window -t -1 -d
bind N swap-window -t +1 -d
# }}}

# Choose {{{
bind w run-shell '$XDG_CONFIG_HOME/tmux/scripts/window-picker'
bind s run-shell '$XDG_CONFIG_HOME/tmux/scripts/session-picker'
# }}}

# Split {{{
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
# }}}

# Switch pane {{{
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind -n S-left  select-pane -L
bind -n S-down  select-pane -D
bind -n S-up    select-pane -U
bind -n S-right select-pane -R
# }}}

# Swap pane {{{
# default: '{'=Down, '}'=Up
bind H if -F '#{>:#{window_panes},1}' 'select-pane -L \; swap-pane -s !' ''
bind J swap-pane -D
bind K swap-pane -U
bind L if -F '#{>:#{window_panes},1}' 'select-pane -R \; swap-pane -s !' ''
# }}}

# Resize pane {{{
bind -r Left  resize-pane -L 2
bind -r Down  resize-pane -D 2
bind -r Up    resize-pane -U 2
bind -r Right resize-pane -R 2
# }}}

# Copy mode {{{
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-line
# }}}

# Send Up and Down keys for the mouse wheel {{{
bind -n WheelUpPane if -Ft= "#{mouse_any_flag}" "send -M" "send Up"
bind -n WheelDownPane if -Ft= "#{mouse_any_flag}" "send -M" "send Down"
# }}}

# Sidebar {{{
bind e run-shell '$XDG_CONFIG_HOME/tmux/scripts/toggle-sidebar agent'
bind y run-shell '$XDG_CONFIG_HOME/tmux/scripts/toggle-sidebar yazi'
# }}}

# Popup $SHELL {{{
unbind t # default 't' is join-pane, explicitly replaced
bind -N 'Toggle popup shell' t if-shell -F '#{==:#{session_name},popup}' \
  'detach-client' \
  'display-popup -d "#{pane_current_path}" -w 80% -h 70% -E "tmux new-session -A -s popup -c \"#{pane_current_path}\" \"$SHELL\""'
# }}}
